'use client';

import React, { useEffect, useState } from 'react';
import { Package, ShieldAlert, Trash2, Loader2, Calendar, User } from 'lucide-react';

interface AdminProduct {
    id: string;
    name: string;
    createdAt: string;
    user: {
        email: string;
    };
}

export default function AdminProductsPage() {
    const [products, setProducts] = useState<AdminProduct[]>([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState('');
    const [deletingId, setDeletingId] = useState<string | null>(null);

    useEffect(() => {
        fetchProducts();
    }, []);

    const fetchProducts = async () => {
        try {
            const res = await fetch('/api/admin/products');
            if (!res.ok) throw new Error('Failed to load products');
            const data = await res.json();
            setProducts(data.products);
        } catch (err: unknown) {
            if (err instanceof Error) {
                setError(err.message);
            }
        } finally {
            setLoading(false);
        }
    };

    const handleDeleteProduct = async (productId: string) => {
        if (!window.confirm("Are you sure you want to PERMANENTLY delete this user's product?")) return;

        setDeletingId(productId);
        try {
            const res = await fetch(`/api/admin/products?id=${productId}`, {
                method: 'DELETE',
            });

            if (!res.ok) throw new Error('Failed to delete product');

            setProducts(products.filter(p => p.id !== productId));
        } catch (err: unknown) {
            if (err instanceof Error) {
                alert(err.message);
            }
        } finally {
            setDeletingId(null);
        }
    };

    if (loading) return <div className="flex h-64 items-center justify-center">Loading system products...</div>;
    if (error) return <div className="text-red-500 flex items-center"><ShieldAlert className="mr-2" /> {error}</div>;

    return (
        <div className="space-y-6">
            <div>
                <h1 className="text-2xl font-bold text-gray-900 dark:text-white flex items-center gap-2">
                    <Package className="text-purple-600" /> System Products
                </h1>
                <p className="text-gray-500 dark:text-gray-400 mt-1">View and manage all products generated by users across the entire platform.</p>
            </div>

            <div className="bg-white dark:bg-zinc-800 shadow rounded-lg overflow-hidden border border-gray-200 dark:border-zinc-700">
                <table className="min-w-full divide-y divide-gray-200 dark:divide-zinc-700">
                    <thead className="bg-gray-50 dark:bg-zinc-800/50">
                        <tr>
                            <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Product Name</th>
                            <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Owner Email</th>
                            <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Generated On</th>
                            <th scope="col" className="relative px-6 py-3"><span className="sr-only">Actions</span></th>
                        </tr>
                    </thead>
                    <tbody className="bg-white dark:bg-zinc-800 divide-y divide-gray-200 dark:divide-zinc-700">
                        {products.length === 0 ? (
                            <tr>
                                <td colSpan={4} className="px-6 py-12 text-center text-sm text-gray-500 dark:text-gray-400">
                                    No products have been generated on the platform yet.
                                </td>
                            </tr>
                        ) : products.map((product) => (
                            <tr key={product.id} className="hover:bg-gray-50 dark:hover:bg-zinc-700/50 transition-colors">
                                <td className="px-6 py-4">
                                    <div className="flex items-center">
                                        <div className="h-8 w-8 rounded-lg bg-purple-100 dark:bg-purple-900/30 flex items-center justify-center text-purple-600 dark:text-purple-400 mr-3">
                                            <Package size={16} />
                                        </div>
                                        <div className="text-sm font-medium text-gray-900 dark:text-white">
                                            {product.name || 'Untitled Product'}
                                            <div className="text-xs text-gray-500 dark:text-gray-400 font-mono mt-0.5">ID: {product.id}</div>
                                        </div>
                                    </div>
                                </td>

                                <td className="px-6 py-4 whitespace-nowrap">
                                    <div className="flex items-center text-sm text-gray-600 dark:text-gray-300">
                                        <User size={14} className="mr-2 text-gray-400" />
                                        {product.user.email}
                                    </div>
                                </td>

                                <td className="px-6 py-4 whitespace-nowrap">
                                    <div className="flex items-center text-sm text-gray-600 dark:text-gray-300">
                                        <Calendar size={14} className="mr-2 text-gray-400" />
                                        {new Date(product.createdAt).toLocaleString()}
                                    </div>
                                </td>

                                <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                    <button
                                        onClick={() => handleDeleteProduct(product.id)}
                                        disabled={deletingId === product.id}
                                        className="text-red-500 hover:text-red-700 dark:text-red-400 dark:hover:text-red-300 transition-colors disabled:opacity-50 flex items-center justify-end w-full"
                                        title="Force Delete Product"
                                    >
                                        {deletingId === product.id ? <Loader2 size={16} className="animate-spin" /> : <Trash2 size={16} />}
                                    </button>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
}
